# Generated by Django 4.1.5 on 2023-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
