# Generated by Django 4.1.5 on 2023-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='cost',
            field=models.FloatField(default=0, null=True),
        ),
    ]
