version: '3.3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-drfr
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - drfr-network
    volumes:
      - ./data/db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 2s

  backend:
    build:
      context: ./docker
      target: drf
      args:
        UID: ${UID}
    container_name: backend_drfr
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/:/opt/app
    ports:
      - "8000:8000"
    networks:
      - drfr-network

  frontend:
    build:
      context: ./docker
      target: react
      args:
        UID: ${UID}
    container_name: frontend_drfr
    command: npm run start
    depends_on:
      backend:
        condition: service_started
      mysql:
        condition: service_healthy
    volumes:
      - ./frontend/:/var/www
    ports:
      - "3000:3000"
    networks:
      - drfr-network

networks:
  drfr-network:
