# Generated by Django 4.1.5 on 2023-02-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_remove_bike_slot'),
        ('slots', '0003_alter_slot_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='bike',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bikes', to='bikes.bike'),
        ),
    ]
