# Generated by Django 4.1.5 on 2023-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_alter_slot_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='number',
            field=models.IntegerField(db_index=True),
        ),
    ]
