# Generated by Django 4.1.5 on 2023-02-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('slots', '0005_alter_slot_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('number', 'station')},
        ),
    ]
