# Generated by Django 4.1.5 on 2023-01-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
